kafka.bootstrap.server.url=4.187.173.203:9096
kafka.username=ewaed6hp3rkggqk477ng4zas1
kafka.password=MrSV45FrMCa36Y7
schema.registry.url=http://karapace-schema-registry.schema-registry:8081
string.input.topic.name=
sequential.keys.or.random=sequential
num.car.keys=1000000
num.bike.keys=1

avro.input.topic.name=
protobuf.input.topic.name=
json.input.topic.name=test-car-nested-json