// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/schema/car.proto
// Protobuf Java Version: 4.33.4

package com.example.GenericProducer.schema;

@com.google.protobuf.Generated
public final class CarProto extends com.google.protobuf.GeneratedFile {
  private CarProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "CarProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.GenericProducer.schema.Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string carId = 1;</code>
     * @return The carId.
     */
    java.lang.String getCarId();
    /**
     * <code>string carId = 1;</code>
     * @return The bytes for carId.
     */
    com.google.protobuf.ByteString
        getCarIdBytes();

    /**
     * <code>string carNumber = 2;</code>
     * @return The carNumber.
     */
    java.lang.String getCarNumber();
    /**
     * <code>string carNumber = 2;</code>
     * @return The bytes for carNumber.
     */
    com.google.protobuf.ByteString
        getCarNumberBytes();

    /**
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    double getSpeed();

    /**
     * <code>double latitude = 4;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code com.example.GenericProducer.schema.Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.example.GenericProducer.schema.Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 4,
        /* suffix= */ "",
        "Car");
    }
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      carId_ = "";
      carNumber_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.GenericProducer.schema.CarProto.internal_static_com_example_GenericProducer_schema_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.GenericProducer.schema.CarProto.internal_static_com_example_GenericProducer_schema_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.GenericProducer.schema.CarProto.Car.class, com.example.GenericProducer.schema.CarProto.Car.Builder.class);
    }

    public static final int CARID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object carId_ = "";
    /**
     * <code>string carId = 1;</code>
     * @return The carId.
     */
    @java.lang.Override
    public java.lang.String getCarId() {
      java.lang.Object ref = carId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        carId_ = s;
        return s;
      }
    }
    /**
     * <code>string carId = 1;</code>
     * @return The bytes for carId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCarIdBytes() {
      java.lang.Object ref = carId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARNUMBER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object carNumber_ = "";
    /**
     * <code>string carNumber = 2;</code>
     * @return The carNumber.
     */
    @java.lang.Override
    public java.lang.String getCarNumber() {
      java.lang.Object ref = carNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        carNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string carNumber = 2;</code>
     * @return The bytes for carNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCarNumberBytes() {
      java.lang.Object ref = carNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        carNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private double speed_ = 0D;
    /**
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    @java.lang.Override
    public double getSpeed() {
      return speed_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 4;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, carId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carNumber_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, carNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
        output.writeDouble(3, speed_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(4, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(5, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, carId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(carNumber_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, carNumber_);
      }
      if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, speed_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.GenericProducer.schema.CarProto.Car)) {
        return super.equals(obj);
      }
      com.example.GenericProducer.schema.CarProto.Car other = (com.example.GenericProducer.schema.CarProto.Car) obj;

      if (!getCarId()
          .equals(other.getCarId())) return false;
      if (!getCarNumber()
          .equals(other.getCarNumber())) return false;
      if (java.lang.Double.doubleToLongBits(getSpeed())
          != java.lang.Double.doubleToLongBits(
              other.getSpeed())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARID_FIELD_NUMBER;
      hash = (53 * hash) + getCarId().hashCode();
      hash = (37 * hash) + CARNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getCarNumber().hashCode();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.GenericProducer.schema.CarProto.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.GenericProducer.schema.CarProto.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.example.GenericProducer.schema.CarProto.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.GenericProducer.schema.CarProto.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.GenericProducer.schema.Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.GenericProducer.schema.Car)
        com.example.GenericProducer.schema.CarProto.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.GenericProducer.schema.CarProto.internal_static_com_example_GenericProducer_schema_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.GenericProducer.schema.CarProto.internal_static_com_example_GenericProducer_schema_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.GenericProducer.schema.CarProto.Car.class, com.example.GenericProducer.schema.CarProto.Car.Builder.class);
      }

      // Construct using com.example.GenericProducer.schema.CarProto.Car.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        carId_ = "";
        carNumber_ = "";
        speed_ = 0D;
        latitude_ = 0D;
        longitude_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.GenericProducer.schema.CarProto.internal_static_com_example_GenericProducer_schema_Car_descriptor;
      }

      @java.lang.Override
      public com.example.GenericProducer.schema.CarProto.Car getDefaultInstanceForType() {
        return com.example.GenericProducer.schema.CarProto.Car.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.GenericProducer.schema.CarProto.Car build() {
        com.example.GenericProducer.schema.CarProto.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.GenericProducer.schema.CarProto.Car buildPartial() {
        com.example.GenericProducer.schema.CarProto.Car result = new com.example.GenericProducer.schema.CarProto.Car(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.GenericProducer.schema.CarProto.Car result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.carId_ = carId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.carNumber_ = carNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.longitude_ = longitude_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.GenericProducer.schema.CarProto.Car) {
          return mergeFrom((com.example.GenericProducer.schema.CarProto.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.GenericProducer.schema.CarProto.Car other) {
        if (other == com.example.GenericProducer.schema.CarProto.Car.getDefaultInstance()) return this;
        if (!other.getCarId().isEmpty()) {
          carId_ = other.carId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCarNumber().isEmpty()) {
          carNumber_ = other.carNumber_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getSpeed()) != 0) {
          setSpeed(other.getSpeed());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getLatitude()) != 0) {
          setLatitude(other.getLatitude());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getLongitude()) != 0) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                carId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                carNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                speed_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object carId_ = "";
      /**
       * <code>string carId = 1;</code>
       * @return The carId.
       */
      public java.lang.String getCarId() {
        java.lang.Object ref = carId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          carId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string carId = 1;</code>
       * @return The bytes for carId.
       */
      public com.google.protobuf.ByteString
          getCarIdBytes() {
        java.lang.Object ref = carId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string carId = 1;</code>
       * @param value The carId to set.
       * @return This builder for chaining.
       */
      public Builder setCarId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        carId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string carId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCarId() {
        carId_ = getDefaultInstance().getCarId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string carId = 1;</code>
       * @param value The bytes for carId to set.
       * @return This builder for chaining.
       */
      public Builder setCarIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        carId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object carNumber_ = "";
      /**
       * <code>string carNumber = 2;</code>
       * @return The carNumber.
       */
      public java.lang.String getCarNumber() {
        java.lang.Object ref = carNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          carNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string carNumber = 2;</code>
       * @return The bytes for carNumber.
       */
      public com.google.protobuf.ByteString
          getCarNumberBytes() {
        java.lang.Object ref = carNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string carNumber = 2;</code>
       * @param value The carNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCarNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        carNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string carNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCarNumber() {
        carNumber_ = getDefaultInstance().getCarNumber();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string carNumber = 2;</code>
       * @param value The bytes for carNumber to set.
       * @return This builder for chaining.
       */
      public Builder setCarNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        carNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 3;</code>
       * @return The speed.
       */
      @java.lang.Override
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 3;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(double value) {

        speed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 4;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 4;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 5;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 5;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.GenericProducer.schema.Car)
    }

    // @@protoc_insertion_point(class_scope:com.example.GenericProducer.schema.Car)
    private static final com.example.GenericProducer.schema.CarProto.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.GenericProducer.schema.CarProto.Car();
    }

    public static com.example.GenericProducer.schema.CarProto.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.GenericProducer.schema.CarProto.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_GenericProducer_schema_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_GenericProducer_schema_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/java/schema/car.proto\022\"com.ex" +
      "ample.GenericProducer.schema\"[\n\003Car\022\r\n\005c" +
      "arId\030\001 \001(\t\022\021\n\tcarNumber\030\002 \001(\t\022\r\n\005speed\030\003" +
      " \001(\001\022\020\n\010latitude\030\004 \001(\001\022\021\n\tlongitude\030\005 \001(" +
      "\001B.\n\"com.example.GenericProducer.schemaB" +
      "\010CarProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_GenericProducer_schema_Car_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_com_example_GenericProducer_schema_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_GenericProducer_schema_Car_descriptor,
        new java.lang.String[] { "CarId", "CarNumber", "Speed", "Latitude", "Longitude", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
